// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

import { Montserrat } from "next/font/google";
import localFont from "next/font/local";

/* =========================
   Primary Font – Montserrat
   ========================= */
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Extralight-ish, Regular, Bold
  variable: "--font-primary",
});

/* =========================
   Secondary Font – Avant Garde
   ========================= */
const avantGarde = localFont({
  src: [
    {
      path: "../public/fonts/ITCAvantGardePro-Md.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-secondary",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${avantGarde.variable} bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
